apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app.kubernetes.io/name: nws
spec:
  containers:
  - name: netology-web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: netology-web-service
spec:
  selector:
    app.kubernetes.io/name: nws
  ports:
  - name: nws-tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080
