---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  pre_tasks:
  - name: Copy sysctl.conf
    ansible.builtin.template:
      src: ./config/sysctl.conf
      dest: /etc/sysctl.conf
      mode: 0644

  - name: restart_network
    ansible.builtin.service:
      name: network
      state: restarted
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  pre_tasks:
  - name: Copy sysctl.conf
    ansible.builtin.template:
      src: ./config/sysctl.conf
      dest: /etc/sysctl.conf
      mode: 0644

  - name: restart_network
    ansible.builtin.service:
      name: network
      state: restarted
  roles:
    - vector

- name: Install LightHouse
  hosts: lighthouse
  become: true
  pre_tasks:
  - name: Copy sysctl.conf
    ansible.builtin.template:
      src: ./config/sysctl.conf
      dest: /etc/sysctl.conf
      mode: 0644

  - name: restart_network
    ansible.builtin.service:
      name: network
      state: restarted
  roles:
    - lighthouse
