apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: vol
        hostPath:
          path: /var/data
      containers:
      - name: bbox
        image: busybox:1.28
        command: ['sh', '-c', "while true; do echo test message >> /output/test.txt; sleep 5; done"]
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: mtool
        image: wbitt/network-multitool
        volumeMounts:
        - name: vol
          mountPath: /input
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
---