---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java 11 vars
      set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ java_oracle_jdk_package }}"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        mode: 0755
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ java_home }}"
        mode: 0644
      tags: java
    - name: Extract java in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
        mode: 0755
      tags:
        - java
    - name: Export environment variables
      become: true
      template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
        mode: 0755
      tags: java

- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - name: installing 'apt-transport-https'
      become: true
      apt:
        name: apt-transport-https
        update_cache: true
    - name: set yandex.mirror repo
      become: true
      shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main" >> /etc/apt/sources.list.d/elastic-7.x.list
      args:
        executable: /bin/bash
    - name: installing elasticsearch
      become: true
      apt:
        name: elasticsearch
        update_cache: true
    - name: Set environment Elastic
      become: true
      template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
        mode: 0755
      tags: elastic service autorun and run
    - name: set elastic to autorun and start install
      become: true
      systemd:
        name: elasticsearch
        daemon_reload: true
        enabled: true
        state: started
