apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-mt-service
  template:
    metadata:
      labels:
        app: ng-mt-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
      - name: init-nginx
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nginx-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginx-service; sleep 2; done"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool
  labels:
    tier: node
    app: network-multitool
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: node
      app: ng-mt-service
  template:
    metadata:
      labels:
        tier: node
        app: ng-mt-service
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
---       

# apiVersion: apps/v1
# kind: Pod
# metadata:
#   name: network-multitool-pod
#   labels:
#     tier: node
#     app: network-multitool-pod
# spec:
#   selector:
#     matchLabels:
#       tier: node
#       app: network-multitool-pod
#   template:
#     metadata:
#       labels:
#         tier: node
#         app: network-multitool-pod
#     spec:
#       hostNetwork: true
#       tolerations:
#       - operator: Exists
#         effect: NoSchedule
#       containers:
#       - name: network-multitool
#         image: wbitt/network-multitool
#         env:
#         - name: HTTP_PORT
#           value: "1180"
#         - name: HTTPS_PORT
#           value: "11443"
#         ports:
#         - containerPort: 28080
#           name: http-port
#         - containerPort: 28443
#           name: https-port
#         resources:
#           requests:
#             cpu: "1m"
#             memory: "20Mi"
#           limits:
#             cpu: "10m"
#             memory: "20Mi"
#         securityContext:
#           runAsUser: 0
#           capabilities:
#             add: ["NET_ADMIN"]