apiVersion: v1
kind: Service
metadata:
  name: nginx-mtool-service-np
spec:
  type: NodePort
  selector:
    app: ng-mt-service
  ports:
  - name: nginx-tcp-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  - name: mt-tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
---